server:
  port: 7074
spring:
  application:
    name: DATACOLLECTION-API
  boot:
    admin:
      client:
        url: http://localhost:8080/
    
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/boot7am
    username: root
    password: root
    
  jpa:
     show-sql: true
     database-platform: org.hibernate.dialect.MySQL8Dialect
     hibernate:
      ddl-auto: update
  #data:
   #  mongodb:
    #  host: localhost
     # database : shopdb 
      #port: 27017
     
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
management:
  endpoints:
    web:
      exposure:
        include: '*'

